Repository AmazingEffect/pulse-content, pull requests merged in 2025-02, with the labels that each got.

#16 Mp 35 sena factory method
  src/main/java/com/pulse/content/adapter/out/persistence/entity/MemberEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/ReactionEntity.java
  src/main/java/com/pulse/content/domain/Member.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/Reaction.java
Labels: 리팩토링

#17 [MP-38] :sparkles: repository 구성
  src/main/java/com/pulse/content/adapter/out/persistence/repository/CategoryRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/CommentRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/HashTagRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/QuoteRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/ReportRepository.java
Labels: 신규기능 개발

#18 [MP-39] :sparkles: create entity repository
  src/main/java/com/pulse/content/adapter/out/persistence/repository/MemberRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/PostRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/ReactionRepository.java
Labels: 신규기능 개발

#19 [MP-40] :sparkles: enum 공통 패키지 생성
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostStatus.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/ReactionEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/ReportEntity.java
  src/main/java/com/pulse/content/common/enumerate/PostStatus.java
  src/main/java/com/pulse/content/common/enumerate/PostVisibility.java
  src/main/java/com/pulse/content/common/enumerate/ReactionType.java
  src/main/java/com/pulse/content/common/enumerate/TargetType.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/Reaction.java
  src/main/java/com/pulse/content/domain/Report.java
Labels: 리팩토링

#20 [MP-41] :sparkles: create contentOutbox entity and domain
  src/main/java/com/pulse/content/adapter/out/persistence/adapter/ContentOutboxPersistAdapter.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/ContentOutboxEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/ContentOutboxRepository.java
  src/main/java/com/pulse/content/application/port/out/CreateContentOutboxPort.java
  src/main/java/com/pulse/content/application/port/out/FindContentOutboxPort.java
  src/main/java/com/pulse/content/application/service/ContentOutboxService.java
  src/main/java/com/pulse/content/common/enumerate/MessageStatus.java
  src/main/java/com/pulse/content/domain/ContentOutbox.java
  src/main/java/com/pulse/content/exception/ErrorCode.java
  src/main/java/com/pulse/content/mapper/ContentOutboxMapper.java
Labels: 신규기능 개발

#22 Mp 44 ann 게시글 작성
  src/main/java/com/pulse/content/adapter/in/web/controller/CreateContentController.java
  src/main/java/com/pulse/content/adapter/in/web/dto/request/CreateContentRequestDTO.java
  src/main/java/com/pulse/content/adapter/in/web/dto/response/CreateContentResponseDTO.java
  src/main/java/com/pulse/content/adapter/out/persistence/adapter/ContentOutboxPersistAdapter.java
  src/main/java/com/pulse/content/adapter/out/persistence/adapter/CreateContentPersistAdapter.java
  src/main/java/com/pulse/content/application/port/in/outbox/CreateContentsUseCase.java
  src/main/java/com/pulse/content/application/port/out/CreateContentPort.java
  src/main/java/com/pulse/content/application/service/CreateContentService.java
  src/main/java/com/pulse/content/common/enumerate/PostStatus.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/key/CategoryId.java
  src/main/java/com/pulse/content/domain/key/CommentId.java
  src/main/java/com/pulse/content/domain/key/HasTagId.java
  src/main/java/com/pulse/content/domain/key/QuoteId.java
  src/main/java/com/pulse/content/domain/key/ReactionId.java
  src/main/java/com/pulse/content/domain/key/ReportId.java
  src/main/java/com/pulse/content/mapper/ContentMapper.java
Labels: 신규기능 개발

#24 Mp 46 ann create mapping table
  src/main/java/com/pulse/content/adapter/out/persistence/entity/CategoryEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/mapping/PostCategoryEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/mapping/PostCategoryRepository.java
  src/main/java/com/pulse/content/application/service/CreateContentService.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/mapping/PostCategory.java
  src/main/java/com/pulse/content/domain/mapping/key/PostCategoryId.java
  src/main/java/com/pulse/content/mapper/ContentMapper.java
Labels: 신규기능 개발

#25 Mp 47 sena 매핑 테이블 생성
  src/main/java/com/pulse/content/adapter/out/persistence/entity/HashTagEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostHashTagMapEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/PostHashTagMapRepository.java
  src/main/java/com/pulse/content/domain/PostHashTag.java
  src/main/java/com/pulse/content/domain/key/PostHashTagId.java
Labels: 신규기능 개발

#26 :recycle: rename file
  src/main/java/com/pulse/content/adapter/out/persistence/entity/CategoryEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/map/PostCategoryMapEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/map/PostHashTagMapEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/PostHashTagMapRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/mapping/PostCategoryRepository.java
Labels: 리팩토링

#27 ♻️ 코드 리팩토링
  src/main/java/com/pulse/content/adapter/out/persistence/repository/map/PostCategoryRepository.java
  src/main/java/com/pulse/content/adapter/out/persistence/repository/map/PostHashTagMapRepository.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/key/PostCategoryId.java
  src/main/java/com/pulse/content/domain/map/PostCategory.java
  src/main/java/com/pulse/content/domain/map/PostHashTag.java
  src/main/java/com/pulse/content/mapper/PostCategoryMapper.java
Labels: 리팩토링

#28 Mp 49 ann 게시글 작성 상세 로직 추가
  src/main/java/com/pulse/content/adapter/in/web/dto/request/CreateContentRequestDTO.java
  src/main/java/com/pulse/content/adapter/in/web/dto/response/CreateContentResponseDTO.java
  src/main/java/com/pulse/content/adapter/out/persistence/adapter/CreateContentPersistAdapter.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/CategoryEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/CommentEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/HashTagEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/QuoteEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/ReportEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/map/PostCategoryMapEntity.java
  src/main/java/com/pulse/content/application/service/CreateContentService.java
  src/main/java/com/pulse/content/domain/Category.java
  src/main/java/com/pulse/content/domain/Comment.java
  src/main/java/com/pulse/content/domain/HashTag.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/Quote.java
  src/main/java/com/pulse/content/domain/Report.java
  src/main/java/com/pulse/content/domain/key/PostCategoryId.java
  src/main/java/com/pulse/content/domain/key/PostCategoryMapId.java
  src/main/java/com/pulse/content/domain/map/PostCategoryMap.java
  src/main/java/com/pulse/content/mapper/ContentMapper.java
  src/main/java/com/pulse/content/mapper/PostCategoryMapper.java
Labels: 버그해결, 리팩토링

#30 Mp 49 ann 게시글 작성 상세 로직 추가
  src/main/java/com/pulse/content/adapter/out/persistence/entity/PostEntity.java
  src/main/java/com/pulse/content/adapter/out/persistence/entity/vo/PostAttachmentEntity.java
  src/main/java/com/pulse/content/common/enumerate/AttachmentType.java
  src/main/java/com/pulse/content/domain/Post.java
  src/main/java/com/pulse/content/domain/vo/ContentDetail.java
  src/main/java/com/pulse/content/domain/vo/PostAttachment.java
  src/main/java/com/pulse/content/mapper/ContentMapper.java
  src/main/java/com/pulse/content/mapper/PostAttachmentMapper.java
  src/main/java/com/pulse/content/mapper/PostCategoryMapper.java
  src/main/java/com/pulse/content/mapper/helper/ContentMapperHelper.java
Labels: 리팩토링, 신규기능 개발
